/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import arquivs.java.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.UsuarioDao;

/**
 *
 * @author Kaique Alves
 */
public class TelaLogin_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin_Cadastro
     */
    public TelaLogin_Cadastro() {
        super("Cadastro");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginCadTextField = new javax.swing.JTextField();
        SenhaCadTextField = new javax.swing.JTextField();
        SenhaCadTextField2 = new javax.swing.JTextField();
        CadLoginButton = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        loginCadTextField.setBackground(new java.awt.Color(255, 204, 204));
        loginCadTextField.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        loginCadTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Login a ser Cadastrado:"));
        getContentPane().add(loginCadTextField);
        loginCadTextField.setBounds(193, 33, 848, 99);

        SenhaCadTextField.setBackground(new java.awt.Color(255, 204, 204));
        SenhaCadTextField.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        SenhaCadTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a senha para o cadastro:"));
        getContentPane().add(SenhaCadTextField);
        SenhaCadTextField.setBounds(193, 164, 848, 100);

        SenhaCadTextField2.setBackground(new java.awt.Color(255, 204, 204));
        SenhaCadTextField2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        SenhaCadTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite novamente a senha:"));
        getContentPane().add(SenhaCadTextField2);
        SenhaCadTextField2.setBounds(193, 296, 848, 100);

        CadLoginButton.setBackground(new java.awt.Color(255, 204, 204));
        CadLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        CadLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        CadLoginButton.setText("Cadastrar");
        CadLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CadLoginButton);
        CadLoginButton.setBounds(429, 428, 479, 163);

        Return.setBackground(new java.awt.Color(255, 204, 204));
        Return.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Return.setForeground(new java.awt.Color(255, 255, 255));
        Return.setText("Voltar");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return);
        Return.setBounds(1040, 570, 207, 103);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Captura de tela 2024-06-04 212012.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1290, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadLoginButtonActionPerformed
        Usuario usuario = new Usuario();
        UsuarioDao dao = new UsuarioDao();
        usuario.setLogin(loginCadTextField.getText());
        if (SenhaCadTextField.getText().equals(SenhaCadTextField2.getText())) {
            usuario.setSenha(SenhaCadTextField.getText());
            try {
                dao.cadastrar(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaLogin_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
        }
        else{
            JOptionPane.showMessageDialog(null, "Senhas não compativeis");
        }
        
    }//GEN-LAST:event_CadLoginButtonActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }//GEN-LAST:event_ReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadLoginButton;
    private javax.swing.JButton Return;
    private javax.swing.JTextField SenhaCadTextField;
    private javax.swing.JTextField SenhaCadTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loginCadTextField;
    // End of variables declaration//GEN-END:variables
}
