/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.precification;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import model.dao.IngredienteDao;

/**
 *
 * @author Kaique Alves
 */
public class TelaReceita_2 extends javax.swing.JFrame {
    
    public TelaReceita_2() throws SQLException, ClassNotFoundException {
        super("Tela de adicionar Receitas");
        initComponents();
        this.setLocationRelativeTo(null);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        loadIngredients();
    }

    private void loadIngredients() throws SQLException, ClassNotFoundException{
        IngredienteDao dao = new IngredienteDao();
        List<String> products = dao.fetchAllProducts();
        for (String product : products){
            IngredientesComboBox.addItem(product);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receitaReturn = new javax.swing.JButton();
        AddNomeReceitaTextField = new javax.swing.JTextField();
        IngredientesComboBox = new javax.swing.JComboBox<>();
        QuantIngredieTextField = new javax.swing.JTextField();
        AddIngReceita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IngredietesReceitaTable = new javax.swing.JTable();
        TempoGastoTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        DTTempoGastoLabel = new javax.swing.JLabel();
        SalarioTempoGastoLabel1 = new javax.swing.JLabel();
        MargemDescTextField = new javax.swing.JTextField();
        DescontoLabel = new javax.swing.JLabel();
        MargemLucroTextField1 = new javax.swing.JTextField();
        LucroLabel = new javax.swing.JLabel();
        ReceitaValorFinalLabel = new javax.swing.JLabel();
        SalvarReceitaButton = new javax.swing.JButton();
        metricaRecComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        receitaReturn.setText("Voltar");
        receitaReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaReturnActionPerformed(evt);
            }
        });

        AddNomeReceitaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita de :"));

        IngredientesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione o Ingrediente>" }));
        IngredientesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientesComboBoxActionPerformed(evt);
            }
        });

        QuantIngredieTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade do Ingrediente usado:"))));
        QuantIngredieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantIngredieTextFieldActionPerformed(evt);
            }
        });

        AddIngReceita.setText("Add");

        IngredietesReceitaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ingrediente:", "Quantidade:", "Metrica:", "Custo de uso:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(IngredietesReceitaTable);

        TempoGastoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo gasto:"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horas", "Minutos", "Dias", "Meses", "Anos" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo gasto em :"));

        DTTempoGastoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("13° e ferias pelo tempo de produção:"));

        SalarioTempoGastoLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Salário pelo tempo de produção:"));

        MargemDescTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Margem de Desconto:"));

        DescontoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor de Desconto:"));

        MargemLucroTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Margem de Lucro:"));

        LucroLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Receber de Lucro:"));

        ReceitaValorFinalLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor final do Produto :"));

        SalvarReceitaButton.setText("Salvar");

        metricaRecComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Escolha uma opção de Metrica>", "Ml(mililitros)", "L (Litros)", "g (gramas)", "kg (Quilos)", "U (Unidades)" }));
        metricaRecComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metricaRecComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddNomeReceitaTextField)
                        .addGap(18, 18, 18)
                        .addComponent(receitaReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IngredientesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(QuantIngredieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(metricaRecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddIngReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TempoGastoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SalarioTempoGastoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DTTempoGastoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MargemLucroTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LucroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MargemDescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DescontoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReceitaValorFinalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SalvarReceitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receitaReturn)
                    .addComponent(AddNomeReceitaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IngredientesComboBox)
                    .addComponent(QuantIngredieTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(metricaRecComboBox)
                    .addComponent(AddIngReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TempoGastoTextField)
                        .addComponent(jComboBox1)
                        .addComponent(SalarioTempoGastoLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                    .addComponent(DTTempoGastoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DescontoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MargemLucroTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LucroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MargemDescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReceitaValorFinalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(SalvarReceitaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receitaReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitaReturnActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }//GEN-LAST:event_receitaReturnActionPerformed

    private void QuantIngredieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantIngredieTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantIngredieTextFieldActionPerformed

    private void IngredientesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientesComboBoxActionPerformed

    private void metricaRecComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metricaRecComboBoxActionPerformed
 JComboBox<String> metricaRecComboBox = new JComboBox <>();
        metricaRecComboBox.addItem("Ml(mililitros)");
        metricaRecComboBox.addItem("L (Litros)");
        metricaRecComboBox.addItem("g (gramas)");
        metricaRecComboBox.addItem("kg (Quilos)");
        metricaRecComboBox.addItem("U (Unidades)");

        String metricaSelect = (String)metricaRecComboBox.getSelectedItem();        // TODO add your handling code here:
    }//GEN-LAST:event_metricaRecComboBoxActionPerformed

    
    
    
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIngReceita;
    private javax.swing.JTextField AddNomeReceitaTextField;
    private javax.swing.JLabel DTTempoGastoLabel;
    private javax.swing.JLabel DescontoLabel;
    private javax.swing.JComboBox<String> IngredientesComboBox;
    private javax.swing.JTable IngredietesReceitaTable;
    private javax.swing.JLabel LucroLabel;
    private javax.swing.JTextField MargemDescTextField;
    private javax.swing.JTextField MargemLucroTextField1;
    private javax.swing.JTextField QuantIngredieTextField;
    private javax.swing.JLabel ReceitaValorFinalLabel;
    private javax.swing.JLabel SalarioTempoGastoLabel1;
    private javax.swing.JButton SalvarReceitaButton;
    private javax.swing.JTextField TempoGastoTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> metricaRecComboBox;
    private javax.swing.JButton receitaReturn;
    // End of variables declaration//GEN-END:variables
}
